### ISSUE TITLE
retrieve urdf parameters from robot_description with namespace

### ISSUE THREAD

**Issue by jacknlliu** [ros/kdl_parser#26]
The `treeFromParam()` can't set the param from some namespace.
https://github.com/ros/kdl_parser/blob/9c6c7c60f27245d5a7ea9c38ec6f96ac6557c3b2/kdl_parser_py/kdl_parser_py/urdf.py#L22

**Comment by clalancette** [comment]
Hm, it's a good point.  Unfortunately, I won't have time to look into it, so if you want to see it fixed please consider opening a pull request that fixes it.  Thanks!
