### ISSUE TITLE
logging issue

### ISSUE THREAD

**Issue by yuraSomatic** [ros/kdl_parser#50]
[foxy branch]
Why do you use fprintf(...), not RCLCPP_DEBUG|INFO|WARN|ERROR|FATAL(...) ?
I can't filter fprintf() via:
rcutils_logging_set_default_logger_level(LOG-LEVEL);
rcutils_logging_set_logger_level(LOGGER_NAME, LOG-LEVEL);

**Comment by clalancette** [comment]
There are a few answers to that:

1. This package was ported to ROS 2 in the days before `RCLCPP_DEBUG` and friends were available.
2. This package currently has no dependency on `rclcpp`, and we would prefer not to add one.
3. There is no node attached to the functions here, so it's not clear what to pass in for the logger.

One way to get around this is to use the `RCUTILS_LOG_DEBUG` macros instead.  `kdl_parser` already has an (indirect) dependency on `rcutils`, so it doesn't add a new dependency, and those macros don't need an `rclcpp::Node` instance to function.  If you'd like to submit a PR to make that change, I'd be happy to review it.

**Comment by yuraSomatic** [comment]
Ok, I will look at RCUTILS_LOG_DEBUG soon. Thank's.

ps. about 3.
You can get logger via `rclcpp::get_logger(LOGGER_NAME)`, without creating any nodes. As I understand the logger will be attached to the current target executable as non node logger.
`RCLCPP_DEBUG(rclcpp::get_logger(LOGGER_NAME), LOG_TEXT);`
`rcutils_logging_set_logger_level(LOGGER_NAME, LOG-LEVEL);`
