### ISSUE TITLE
Branch kdl_parser for Galactic

### ISSUE THREAD

**Issue by sloretz** [ros/kdl_parser#53]
@clalancette any objections?

This one seems easy: create a `galactic` branch from the `ros2` branch and update rosdistro to say `galactic` is the devel branch.

**Comment by clalancette** [comment]
Yes, it looks like we've made branches for all other ros2 releases, so I think we should be consistent here and make a galactic branch.

**Comment by sloretz** [comment]
It looks like the branch has been created and [`ros/rosdistro` already has the updated branch](https://github.com/ros/rosdistro/blob/8916fda922fba94107bf01cee956168b19bba1dd/galactic/distribution.yaml#L1029-L1044). I updated the release repo in https://github.com/ros2-gbp/kdl_parser-release/commit/09ab79474a217834258fcf5a618ba453c73178f9 . Closing.
