### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'getChain'

### ISSUE THREAD

**Issue by adhitir-magna** [ros/kdl_parser#56]
Getting this attribute error.
```
AttributeError: 'tuple' object has no attribute 'getChain'
```

Environment: Ubuntu 18.04 with ROS Melodic
Robot: UR10e

Script:
```
import PyKDL as kdl
import kdl_parser_py.urdf as kdl_parser
base_link = 'base_link'
ee_link = 'tool0'
tree = kdl_parser.treeFromParam('/robot_description')
chain = tree.getChain("base_link", "tool0")
```

**Comment by clalancette** [comment]
The `treeFromParam` method [returns a tuple](https://github.com/ros/kdl_parser/blob/a1ba6dfffc9c95b30d8a099f8785db4cf5c0342f/kdl_parser_py/kdl_parser_py/urdf.py#L128), so you need:

```
import PyKDL as kdl
import kdl_parser_py.urdf as kdl_parser
base_link = 'base_link'
ee_link = 'tool0'
ok, tree = kdl_parser.treeFromParam('/robot_description')
chain = tree.getChain("base_link", "tool0")
```

In the future, please ask questions like this on https://answers.ros.org, which is our centralized place for questions and answers.  Closing this issue.
