### ISSUE TITLE
foxy compile kdl_parser_py failed on Jetson

### ISSUE THREAD

**Issue by beyondli** [ros/kdl_parser#59]
Hi dear,
During my compile code from guide https://docs.ros.org/en/foxy/Installation/Ubuntu-Development-Setup.html and your scritp code on AGX and TX2, both failed on

So I think I need modify this package_dir maybe, because python_setup unrecognize Path “.”
any help is very appreciated!

![image](https://user-images.githubusercontent.com/11239010/140525446-9eb28da9-8980-439c-9afe-662a582ab500.png)

**Comment by clalancette** [comment]
kdl_parser_py is not yet ported to ROS 2; see ros/kdl_parser_py#2.  As such, I'm going to close this out for now.
