### ISSUE TITLE
AUR package  ros-melodic-kdl-parser-py out of date

### ISSUE THREAD

**Issue by Yuan-Quan** [ros/kdl_parser#62]
[aur: ros-melodic-kdl-parser-py](https://aur.archlinux.org/packages/ros-melodic-kdl-parser-py) is on version 1.13.1

It won't build properly due to #44 

please update it.

**Comment by clalancette** [comment]
The fix in #44 was released into the standard ROS channels long ago (over a year).  Since Arch is not a platform we officially build packages for, you'll need to contact someone on the Arch side to package 1.13.2.
