### ISSUE TITLE
release new changes for noetic and update ros distro

### ISSUE THREAD

**Issue by sonelu** [ros/kdl_parser#63]
Hi, it looks like changes after Aug 2020 (like #45) are not included in a release and therefore not available through the official noetic distro.

Could you please release an updated version and update the official [distro](https://github.com/ros/rosdistro/blob/5a86d4953ade45134a8cec7065b02ef163b9900f/noetic/distribution.yaml#L3960)?

Thanks.

**Comment by clalancette** [comment]
I've done releases for Melodic and Noetic in https://github.com/ros/rosdistro/pull/32759 and https://github.com/ros/rosdistro/pull/32760 .
